import type { WorkflowParameter } from '@browser-persona/shared';
import { checkpointExpression, type TemplateStep } from './steps.js';

export interface ExportOptions {
  capabilityId: string;
  capabilityName: string;
  description?: string;
  stepTemplate: TemplateStep[];
  parameters?: WorkflowParameter[];
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
}

export function exportPlaywrightScript(options: ExportOptions): string {
  const slug = slugify(options.capabilityName) || 'capability';
  const paramEntries = (options.parameters ?? []).map((p) => {
    const example = p.example ?? '';
    return `  ${JSON.stringify(p.name)}: process.env[${JSON.stringify(p.name.toUpperCase())}] ?? ${JSON.stringify(example)},`;
  });

  const stepLines = options.stepTemplate.flatMap((step, index) => checkpointExpression(index, step));

  return `/**
 * Generated by Browser Persona
 * Capability: ${options.capabilityName}
 * ID: ${options.capabilityId}
${options.description ? ` * ${options.description}\n` : ''} *
 * Run headful:
 *   npx tsx ${slug}.playwright.ts
 *
 * Override parameters via env, e.g. START_DATE=2026-06-01
 */
import { chromium } from 'playwright';

const params: Record<string, string> = {
${paramEntries.join('\n')}
};

async function runCapability() {
  const browser = await chromium.launch({ headless: false, slowMo: 50 });
  const page = await browser.newPage();

  try {
${stepLines.map((line) => `    ${line}`).join('\n')}
    console.log('All checkpoints passed.');
  } catch (err) {
    console.error('Capability run failed:', err);
    const html = await page.content();
    console.error('DOM snapshot (truncated):\\n', html.slice(0, 8000));
    process.exitCode = 1;
  } finally {
    await browser.close();
  }
}

runCapability();
`;
}
